# Generated by Django 5.2.3 on 2025-06-27 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="approved",
        ),
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="submitted",
                help_text="Current review status of the article",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                help_text="Author (must be a journalist)",
                limit_choices_to={"role": "journalist"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional publisher",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to="core.publisher",
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="editors",
            field=models.ManyToManyField(
                help_text="Editors assigned to this publisher",
                limit_choices_to={"role": "editor"},
                related_name="publisher_editors",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="journalists",
            field=models.ManyToManyField(
                help_text="Journalists who write under this publisher",
                limit_choices_to={"role": "journalist"},
                related_name="publisher_journalists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
