# Generated by Django 5.2.3 on 2025-06-29 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_article_approved_article_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="is_deleted",
            field=models.BooleanField(default=False, help_text="Soft delete flag"),
        ),
    ]
