# Generated by Django 5.2.3 on 2025-06-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_article_deleted_at_article_is_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
