# Generated by Django 5.2.3 on 2025-06-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_article_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bookmarked_articles",
            field=models.ManyToManyField(
                blank=True, related_name="bookmarked_by", to="core.article"
            ),
        ),
    ]
