# Generated by Django 5.2.3 on 2025-06-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_article_view_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("reader", "Reader"),
                    ("journalist", "Journalist"),
                    ("editor", "Editor"),
                ],
                default="reader",
                max_length=20,
            ),
        ),
    ]
