# Generated by Django 5.2.3 on 2025-06-30 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="editor_comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
