# Generated by Django 5.2.3 on 2025-06-30 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_article_editor_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="editor_comment",
            new_name="rejection_reason",
        ),
    ]
