# Generated by Django 5.2.3 on 2025-07-04 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_rename_editor_comment_article_rejection_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="owner",
            field=models.OneToOneField(
                blank=True,
                help_text="User who owns this publisher profile",
                limit_choices_to={"role": "publisher"},
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="publisher_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("reader", "Reader"),
                    ("journalist", "Journalist"),
                    ("editor", "Editor"),
                    ("publisher", "Publisher"),
                ],
                default="reader",
                max_length=20,
            ),
        ),
    ]
