# Generated by Django 5.2.3 on 2025-07-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_newsletter_published_at_newsletter_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="newsletter",
            old_name="published_at",
            new_name="approved_at",
        ),
        migrations.AddField(
            model_name="newsletter",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="newsletter",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="submitted",
                max_length=10,
            ),
        ),
    ]
