version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DJANGO_SETTINGS_MODULE=news_portal.settings
      - DB_HOST=db
      - DB_NAME=news_db
      - DB_USER=root
      - DB_PASSWORD=mole@2018

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_DATABASE: news_db
      MYSQL_ROOT_PASSWORD: mole@2018
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
