version: "3.9"

services:
  web:
    build:
      context: .            # Builds from current dir: repo/news_portal
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app              # Mounts repo/news_portal into /app
    environment:
      - IN_DOCKER=0
      - DB_NAME=news_db
      - DB_USER=root
      - DB_PASSWORD=mole@2018
      - DB_HOST=db
      - DB_PORT=3306
    working_dir: /app       # Ensures Python runs in /app where manage.py is
    command: >
      sh -c "
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000
      "
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mariadb:10.6.22
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mole@2018
      MYSQL_DATABASE: news_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-pmole@2018", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

      retries: 5

volumes:
  db_data:
